### ISSUE TITLE
TO DO: Switch to MBR layout

### ISSUE THREAD

**Issue by mrclksr** [nomadbsd/NomadBSD#15]
**Problem**
Setting the `lenovofix` attribute on the MBR of a GPT partitioned disk makes booting possible for Lenovo models affected by a certain [BIOS bug](https://lists.freebsd.org/pipermail/freebsd-i386/2013-March/010437.html). Some systems however (e.g. Dell Precision M3800) get stuck when trying to boot from such a disk.

**Solution**
Drop GPT, and switch to the old MBR layout. This requires changing the build-, setup-, reset- and install script. GPT can still be used for the target disk in `nomadbsd-install`, but requires a `lenovofix` option for the user to choose.

Update: https://github.com/nomadbsd/NomadBSD/tree/mbr

**Comment by allentiak** [comment]
I agree on that there is a problem here. That being said... Could it be that, perhaps, the approach to tackle it could be a little bit less drastic?

I wonder... Is it really necessary to ditch GPT altogether because of this? It has been the main (if not only) layout used in modern computers for years already. Therefore, I would estimate there may be only a handful of people who would, nowadays, install an OS that doesn't support it...
Maybe, there is a way to maintain both Legacy and UEFI booting?

May I humbly propose considering a different approach? What about starting by researching on how other distributions go about this problem. Chances are, there just might be one or two things to learn from how other similar, more experienced projects that have been running for years (be them either *BSD-based or GNU/Linux-based) tackle this situation...

**Comment by mrclksr** [comment]
@allentiak 
GPT is still used for HDD installations and for the Mac image. Only the live system uses the MBR layout which is the same FreeBSD uses for their memstick images: The first slice (partition) contains a FAT filesystem with the EFI loader. The second slice (partition) contains a bootable UFS filesystem. This allows booting via EFI and BIOS.
